### PR TITLE
Tip button temporary solution 

### LINKED ISSUE #126: Add tip button to the participants lists
Use that util to check if user have chain name or account number and render [tip button](https://github.com/aeternity/jitsi-meet/blob/tip_button/react/features/conference/components/web/TipButton.js) near the user in the lists
https://github.com/aeternity/jitsi-meet/blob/4c08c855909912599541643a38478d261b520ffe/react/features/aeternity/utils.js#L1-L9

Снимок экрана 2020-07-23 в 18 11 39
Снимок экрана 2020-07-23 в 18 11 49

### PR DESCRIPTION
**Pull request by shapkarin**

### CODE REVIEW

**Comment by shapkarin** [comment]
TODO: 
- chat tooltip position fix
- normal scroll for thumbnails list (check the flex direction)

**Comment by venimus** [comment]
image

**Comment by shapkarin** [comment]
Yes, thanks. It need to be poison in different ways for the different lists.

**Comment by venimus** [comment]
image

**Review by DeeJayElly — APPROVED** [review]

**Review by Chima1707 — APPROVED** [review]

**Review by mike-gusev-ae — APPROVED** [review]

**Pull request merged**
