### PR TITLE
No written notifications in the bottom left corner #9

### LINKED ISSUE #9: No written notifications in the bottom left corner

### PR DESCRIPTION
**Pull request by DeeJayElly**
No written notifications in the bottom left corner #9

### CODE REVIEW

**Review by dincho — DISMISSED** [review]
I definitely disagree with this proposition. about 900 lines of upstream code changes is not something that can be maintained in the future.

Also, I don't think ALL notifications should be really removed - like why removing mute/unmute ?!?

If all notifications has to be removed really, I would suggestion adding a bypass in `participantNotification` (configurable).

**Review by dincho — COMMENTED** [review]
Okay, it looks like similar changes has been merged already https://github.com/aeternity/jitsi-meet/commit/186f4eabca843075054f883f550a5a2bbdce0b96

If that approach is already approved. I'm not going to block this one, but I'm not also going to approve such approach.

**Comment by DeeJayElly** [comment]
> I definitely disagree with this proposition. about 900 lines of upstream code changes is not something that can be maintained in the future.
> 
> Also, I don't think ALL notifications should be really removed - like why removing mute/unmute ?!?
> 
> If all notifications has to be removed really, I would suggestion adding a bypass in `participantNotification` (configurable).

Agree @dincho i will adopt my changes

**Comment by DeeJayElly** [comment]
Added new changes

**Review by mradkov — APPROVED** [review]
That looks better. Thanks!

**Pull request merged**
