### PR TITLE
Login with web wallet to the settings #44

### LINKED ISSUE #44: Put `Login with web wallet` in menu
`Login with webwallet` button should be probably somewhere in the menu as well, as it dissapears when there are more than 1 participants. (meaning it is only shown if there is nobody else in the room besides you)

656f21b4-60a7-41a4-8ee1-91e72b5a7b5d

### PR DESCRIPTION
**Pull request by shapkarin**
closes #44

### CODE REVIEW

**Comment by shapkarin** [comment]
I will add the styles as well

**Comment by venimus** [comment]
We would also need it here (it is more important) -along with the I'm the host

image

**Comment by venimus** [comment]
and it does not look styled

image

**Comment by shapkarin** [comment]
@venimus https://github.com/aeternity/jitsi-meet/pull/70#issuecomment-654351090 I will add it today

**Comment by shapkarin** [comment]
> We would also need it here (it is more important) -along with the I'm the host

@venimus It may be useful. But the problem that this button is not so secure as login with sdk. Maybe that's why we hide it to the settings. 

~~@mradkov Also there will be a problem if user try to login with that button not from the room itself but from the room create screen. I will fix that later as well.~~

**Comment by shapkarin** [comment]
I was wrong at https://github.com/aeternity/jitsi-meet/pull/70#issuecomment-654789213 there is no any problem

**Comment by shapkarin** [comment]
@venimus hope this styles are fine

**Comment by venimus** [comment]
unfortunately still looks odd - too much padding at right and also the font is bigger. 

image

**Comment by shapkarin** [comment]
@venimus what browser?

**Comment by shapkarin** [comment]
fixed that
> unfortunately still looks odd - too much padding at right and also the font is bigger.

**Review by DeeJayElly — APPROVED** [review]

**Comment by shapkarin** [comment]
Strange that I don't have styles here. Maybe it's at other PR or reverted with force push

**Comment by shapkarin** [comment]
Yes, they are..

**Pull request merged**
